#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Format Rust files
cd src-tauri && rustup run nightly -- rustfmt ./src/main.rs --edition 2018 --check
cd ..

# Run ESLint
yarn lint

# Run Prettier
yarn format

# Add changes to staging
git add .
